# -*- coding: utf-8 -*-
"""Another copy of day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQ7gM3Zzgf__JE5oM4kY3CvSIdONWoGG
"""

print(""hello"")  # terminates after two " " , use single to put the doubles inside

print("""i am human""")

"i am""this"

a= [
    "ram"
    "hari",
    "sita"
]
a

"""I am ram " # first triple quote is expecting another triple cquote ,it doesnt find it so error

"I am ram""" # the first single wuote findfs another single quote and string ends there , and other 2 considdered as empty string

print("\"hi i am human\"") # putting the \ above any character tells the compiler not to treat it as normal character

# The list of all students' names from :
data = {
'class': 'Grade 5',
'students': [
{'name': 'Alice', 'subjects': {'math': 85, 'science': 92}},
{'name': 'Bob', 'subjects': {'math': 78, 'science': 88}},
{'name': 'Charlie', 'subjects': {'math': 95, 'science': 89}}
],
'teacher': {'name': 'Mrs. Smith', 'subject': 'science'}
}


[student for student in data["students"]]  # makes a list of objs in std of dictionary

[student['name'] for student in data["students"]]   # list comprehension

{student['name'] : student['subjects'] for student in data["students"]}    #making a dictionary

# dictionary comprehrension

(student['name'] for student in data["students"])

reversed([1,2,3])

# <generator object ??? what are they
# how to manually create them ???

#list,dict comprehension
# lazy initialization??

# list of even numbers

even =[ x for x in range(10) if x%2==0]
even

a= [ (x,y) for x in range(5) for y in range(5) if x>y ]
a

# ex 4 qn 12


# Write a list comprehension to create a list of squares for numbers from 1 to 10.
# 13. Use a list comprehension to create a list of even numbers from the list numbers = [1, 2, 3, 4, 5, 6,
# 7, 8, 9, 10].
# 14. Write a dictionary comprehension to create a dictionary where the keys are numbers from 1 to 5
# and the values are the cubes of the keys.
# 15. Use a set comprehension to create a set of unique vowels from the string sentence =
# "comprehensions are powerful".
# 16. Given a dictionary students = {'Alice': 85, 'Bob': 78, 'Charlie': 92, 'David': 63}, write a dictionary
# comprehension to create a new dictionary with students who scored above 80.

# 12 i

sqr= [i*i for i in range(1,10) ]
sqr

#13
even=[ i for i in range(10) if i%2==0]
even

#14
{ i :i*i*i for i in range(1,6)}

#15
vowel=( x for x in "comprehensions are powerful" if x in ('a','e','i','o','u'))
print(set(vowel))

 # without the typecasting , it was creating a generator obj,
#and we cant print it directly , there are separate ftns to print a generator obj
# so first we convert it to set and then print it

# 16. Given a dictionary students = {'Alice': 85, 'Bob': 78, 'Charlie': 92, 'David': 63}, write a dictionary
# comprehension to create a new dictionary with students who scored above 80.

students = {'Alice': 85, 'Bob': 78, 'Charlie': 92, 'David': 63}


passed = { i:j for i,j in students.items() if j>80 }
print(passed)



for keys,values in students.items():
  print(keys,values)

students = {'Alice': 85, 'Bob': 78, 'Charlie': 92, 'David': 63}
dir(students)



a=[(1,2),(3,4),(5,6)]

for i,j in a:
  print(j,i)     # does one to one mapping

"""# create new list of higher or lower by checking next element"""

# create new list of higher or lower by checking next element

l = [1,2,3,4,5,1,2,3]
neww=[]
for i in range(len(l)-1):
    for j in range(i+1 ,range(len(l))-1):
      if l[j]>l[i]:
        neww.append("higher")
      else:
        neww.append("lower")
print(neww)

# raymond hettinger

# enumerate : returns list of tupples having index and values

l = [1,2,3,4,5,1,2,3]
list(enumerate(l))



# ternary operators in python

a=  1 if True else 2
a

(first value) if (condition) else (second value)

#zip function

zip ( iterable1 , iterable2 , iterable 3 , .. )

it wraps elements from each iterable together , and we can type cast it into anything
a list , tupple or dict

l = [1,2,3,4,5,1,2,3]

new = [ "l" if curr>next else "h"
       for curr,next in zip(l , l[1:])
]
new

z =zip(l, range(3),range(4))
print(list(z))

# ( ............)
# some diff examples of enumerate and zip still left ,,, see in the slide



vowels ="aeiou"

numbers=[1,2,3,4,5]


neww=zip(vowels,numbers)
print(dict(neww))

vowels ="aeiou"

numbers=[1,2,3,4,5]

help(dict)

dict.__doc__  # to see the docstring / documentation





"""file handling

"""

f= open("std.txt:,w)


f,readlines()
f.close()

# with
- auto closes file


# pass
#

# using json data in python - load , save , write















